# Generated by Django 5.2.16 on 2026-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_item_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('abs_library_id', models.CharField(blank=True, max_length=64)),
                ('asin', models.CharField(blank=True, db_index=True, max_length=32)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=32)),
                ('match_key', models.CharField(blank=True, db_index=True, help_text='Normalized title+author; last resort when ABS re-mints an item id.', max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('subtitle', models.CharField(blank=True, max_length=512)),
                ('authors', models.CharField(blank=True, max_length=512)),
                ('narrators', models.CharField(blank=True, max_length=512)),
                ('series', models.CharField(blank=True, max_length=256)),
                ('series_sequence', models.CharField(blank=True, max_length=32)),
                ('publisher', models.CharField(blank=True, max_length=256)),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, upload_to='covers/')),
                ('cover_thumb', models.ImageField(blank=True, upload_to='covers/thumbs/')),
                ('cover_source_hash', models.CharField(blank=True, help_text='Fingerprint of the upstream cover; re-download only when it changes.', max_length=128)),
                ('is_finished', models.BooleanField(db_index=True, default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_orphaned', models.BooleanField(db_index=True, default=False, help_text='Absent from the last sync. Never deleted -- a review may depend on it.')),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['is_finished', 'is_orphaned'], name='catalog_boo_is_fini_d74d90_idx')],
            },
        ),
    ]
