# Generated by Django 5.2.16 on 2026-07-27 15:22

"""The listening record: when a book was started, last touched, and how far it got.

Elapsed time relative to length is the strongest available signal of how much a book
was enjoyed, and silence after a few minutes is how an abandonment is recognised.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_nightly_sync_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_played_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last progress update. Silence since is what marks a book abandoned.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='progress',
            field=models.FloatField(default=0.0, help_text='0..1, from ABS.'),
        ),
        migrations.AddField(
            model_name='book',
            name='seconds_listened',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
