# Generated by Django 5.2.16 on 2026-07-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_listening_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hide_from_public',
            field=models.BooleanField(default=False, help_text='Keep this book out of “now listening” on the public page. The sync never touches this box.'),
        ),
    ]
