# Generated by Django 5.2.16 on 2026-07-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_hide_from_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='abandoned_note',
            field=models.CharField(blank=True, help_text='Why I stopped. “Wrong moment” and “not for me” point a recommender in opposite directions, so say which. Never shown publicly.', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='is_comfort_read',
            field=models.BooleanField(default=False, help_text='What I put on to switch off. Kept out of the taste profile in the LLM export -- offered as a separate appetite instead.', verbose_name='comfort read'),
        ),
    ]
