# Generated by Django 5.2.16 on 2026-07-27 13:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Assigned at first publish, then frozen. Federated links must never 404.', max_length=200, null=True, unique=True)),
                ('rating_overall', models.PositiveSmallIntegerField(help_text='Half-steps: 1–10 renders as 0.5–5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rating_narration', models.PositiveSmallIntegerField(blank=True, help_text='Optional. A great book can have a poor reader.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('summary', models.CharField(help_text='Hand-written. Becomes og:description and, in P2, the Mastodon post — so it should read as a sentence, not a truncated first paragraph.', max_length=300)),
                ('body_markdown', models.TextField(blank=True, help_text='Markdown. Optional.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mastodon_status_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('mastodon_posted_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='catalog.book')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
