# Generated by Django 5.2.16 on 2026-07-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewviewday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='summary',
            field=models.CharField(blank=True, help_text='Optional. Becomes og:description and the Mastodon post, so it should read as a sentence rather than a truncated first paragraph. Leave it empty and the card falls back to the body, then to the rating on its own.', max_length=300),
        ),
    ]
