# Generated by Django 5.2.16 on 2026-07-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='had_orm',
            field=models.BooleanField(default=False, help_text='Rare. Not a higher rating -- a different axis. Tick it only for a book that did something to you beyond being good.', verbose_name='Orm'),
        ),
    ]
