# Generated by Django 5.2.16 on 2026-07-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_had_orm'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='synopsis_markdown',
            field=models.TextField(blank=True, help_text='Optional. Markdown. Plot orientation for someone who has not read the book. Never quoted anywhere the site speaks for me.', verbose_name='Synopsis (LLM)'),
        ),
    ]
